version: '3.9'

services:
  user_quest_app:
    build: ./
    command: ./user_quest_app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      $POSTGRES_PASSWORD: nav461
      POSTGRES_DB: VK_test_GOPHP
    hostname: user_quest_app
    container_name: user_quest_app

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nav461
      POSTGRES_DB: VK_test_GOPHP
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.postgres-data:/var/lib/postgresql/data