# database:
#   username: "your_username"
#   password: "your_password"
#   dbname: "your_database_name"
database:
  username: "postgres"
  password: "nav461"
  dbname: "VK_test_GOPHP"
  host: "localhost"
  port: "5432"